### ISSUE TITLE
[Help]: Node 版本编译问题

### ISSUE THREAD

**Issue by HarvenX** [r3x5ur/unveilr#106]
### unveilr版本

2.0.1

### 操作系统

windows

### 运行时命令

unveilr  -v

### 重现步骤

安装node v18.16.0 
命令行 cd 到达源码根目录
打开\scripts\pkg.js 文件，删除node14-win-x64 以外的targets ,保存退出
命令行输入 node scripts\pkg.js 
报错安装缺少的包 npm install -g pkg  npm install -g compressing 
直到 node scripts\pkg.js  成功运行
获取到[PKG] Generating dest release\unveilr@2.0.1.exe.tar.gz 
解压文件后命令行输入 release\unveilr@2.0.1.exe -v

### 预期结果

成功输出版本号

### 实际结果

D:\-----\unveilr>release\unveilr@2.0.1.exe -v
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: File 'C:\**\unveilr\node_modules\vm2\lib\setup-sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.<anonymous> (C:\snapshot\unveilr\node_modules\vm2\lib\vm.js:145:57)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (pkg/prelude/bootstrap.js:1933:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\unveilr\\node_modules\\vm2\\lib/setup-sandbox.js',
  pkg: true
}

### 其他信息

自己没有node 编译过，编译流程也是多次尝试发现的可行路径。
不确定是不是node 版本或者module的版本是否有问题。

**Comment by r3x5ur** [comment]
切换到node v14 或者将target 配置成 `node18-win-x64`

**Comment by r3x5ur** [comment]
关于版本，我这是使用的`yarn`，并且已经有`yarn.lock` 文件，你使用`yarn`安装依赖的话是可以保持一个正确的环境的， 使用`npm`的话可能有少许版本差异，不清楚会不会造成问题

**Comment by HarvenX** [comment]
目测我比较菜，编译node 还是不行，结果还是一样，用 [107](https://github.com/r3x5ur/unveilr/pull/107) 的方法，我也可以进行解包。
手头工作要紧，晚点再研究怎么编译
我同样也遇到了  [107](https://github.com/r3x5ur/unveilr/pull/107)  这位大佬的问题，也一并被解决。

**Comment by babaloveyou** [comment]
> 切换到node v14 或者将target 配置成 `node18-win-x64`

node v14.0.0 和node v14.21.3 在window10 x64 下用上面的命令编译都是上面同样的错误,这个正确的编译方式是什么
