### ISSUE TITLE
 <GlobalExceptionCaught> ReferenceError: ConfigController is not initialized

### ISSUE THREAD

**Issue by voula32** [r3x5ur/unveilr#28]
**运行环境、版本信息**<br/>
 - OS: Ubuntu 22.04
 - NodeJS: v18.15.0

大佬你好，安卓手机里的小程序包和PC上的都试了，都有是这个错误提示

![1679853691(1)](https://user-images.githubusercontent.com/128997485/227795087-e214cfee-33ba-4f31-be6e-f54eef95d39f.jpg)

**Comment by r3x5ur** [comment]
@voula32 感谢提交，解决中

**Comment by Leepay** [comment]
同样的问题，我的环境是 Win10, NodeJS v18.14.0，使用unveilr@2.0.0-alpha.1-win-x64.exe，报错信息：
```text
[ERROR] 08:41:37 <GlobalExceptionCaught> ReferenceError: ConfigController is not initialized
    at Function.getInstance (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:11742)
    at getConfig (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:11877)
    at getLogger (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:12202)
    at styleConversion (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:20865)
    at TraverseController.CallExpression (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:22603)
    at C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:41421
    at Array.forEach (<anonymous>)
    at r.<computed> (C:\snapshot\unveilr\dist\traverse-0b233d7e.js:7:41407)
    at NodePath._call (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:45:20)
    at NodePath.call (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:35:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:80:31)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\snapshot\unveilr\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
```
看了看我的文件系统，并没有`C:\snapshot\unveilr\`目录

**Comment by r3x5ur** [comment]
[🔖v2.0.0-alpha.2](https://github.com/r3x5ur/unveilr/releases/tag/v2.0.0-alpha.2)

**Comment by r3x5ur** [comment]
@Leepay  `C:\snapshot\unveilr\`是 `pkg` 打包内置的`NodeJS `环境
运行打包后二进制文件就已经脱离本地的`NodeJs`环境了
