### ISSUE TITLE
[Bug]: <Exception> SyntaxError: unknown: Legacy octal literals are not allowed in strict mode

### ISSUE THREAD

**Issue by feiyangboy2** [r3x5ur/unveilr#64]
### unveilr版本

2.0.0-beta.1

### NodeJs版本

v18.14.2

### 操作系统

windows

### 运行时命令

unveilr@2.0.0-beta.1-win-x64.exe wx 

### 重现步骤(最好能上传反编译失败的样本)

..

### 预期结果

   ..

### 实际结果

 [ERROR] 15:57:56 <Exception> SyntaxError: unknown: Legacy octal literals are not allowed in strict mode. (1633:137)

  1631 | Z([a,[[2,'||'],[[12],[[6],[[7],[3,'filters']],[3,'integerBit']],[[5],[[6],[[7],[3,'productList']],[3,'salePriceWithTax']]]],[1,0]]])
  1632 | Z([3,'characterxiaofood'])
> 1633 | Z([a,[3,'.'],[[2,'||'],[[12],[[6],[[7],[3,'filters']],[3,'decimalPlace']],[[5],[[6],[[7],[3,'productList']],[3,'salePriceWithTax']]]],[1,00]]])
       |                                                                                                                                          ^
  1634 | Z([[2,'>'],[[6],[[7],[3,'productList']],[3,'recommendRetailPrice']],[[6],[[7],[3,'productList']],[3,'salePriceWithTax']]])
  1635 | Z([3,'servationXiaofood'])
  1636 | Z([a,[3,'\n            ￥'],[[2,'||'],[[12],[[6],[[7],[3,'filters']],[3,'integerBit']],[[5],[[6],[[7],[3,'productList']],[3,'recommendRetailPrice']]]],[1,0]],z[55][1],[[2,'||'],[[12],[[6],[[7],[3,'filters']],[3,'decimalPlace']],[[5],[[6],[[7],[3,'productList']],[3,'recommendRetailPrice']]]],[1,00]]])
    at instantiate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:653:32)
    at constructor (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:947:12)
    at Parser.raise (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:3261:19)
    at Parser.recordStrictModeErrors (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:3187:12)
    at Parser.readNumber (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:3063:12)
    at Parser.getTokenFromCode (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:2870:14)
    at Parser.nextToken (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:2384:10)
    at Parser.next (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:2305:10)
    at Parser.eat (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:2309:12)
    at Parser.expect (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:3633:10)
    at Parser.parseExprList (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11970:14)
    at Parser.parseArrayLike (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11879:26)
    at Parser.parseExprAtom (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11148:23)
    at Parser.parseExprSubscripts (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10870:23)
    at Parser.parseUpdate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10853:21)
    at Parser.parseMaybeUnary (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10829:23)
    at Parser.parseMaybeUnaryOrPrivate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10667:61)
    at Parser.parseExprOps (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10672:23)
    at Parser.parseMaybeConditional (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10649:23)
    at Parser.parseMaybeAssign (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10610:21)
    at C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:39
    at Parser.allowInAnd (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12255:12)
    at Parser.parseMaybeAssignAllowIn (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:17)
    at Parser.parseExprListItem (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12007:18)
    at Parser.parseExprList (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11979:22)
    at Parser.parseArrayLike (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11879:26)
    at Parser.parseExprAtom (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11148:23)
    at Parser.parseExprSubscripts (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10870:23)
    at Parser.parseUpdate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10853:21)
    at Parser.parseMaybeUnary (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10829:23)
    at Parser.parseMaybeUnaryOrPrivate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10667:61)
    at Parser.parseExprOps (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10672:23)
    at Parser.parseMaybeConditional (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10649:23)
    at Parser.parseMaybeAssign (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10610:21)
    at C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:39
    at Parser.allowInAnd (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12255:12)
    at Parser.parseMaybeAssignAllowIn (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:17)
    at Parser.parseExprListItem (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12007:18)
    at Parser.parseExprList (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11979:22)
    at Parser.parseArrayLike (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11879:26)
    at Parser.parseExprAtom (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11148:23)
    at Parser.parseExprSubscripts (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10870:23)
    at Parser.parseUpdate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10853:21)
    at Parser.parseMaybeUnary (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10829:23)
    at Parser.parseMaybeUnaryOrPrivate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10667:61)
    at Parser.parseExprOps (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10672:23)
    at Parser.parseMaybeConditional (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10649:23)
    at Parser.parseMaybeAssign (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10610:21)
    at C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:39
    at Parser.allowInAnd (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12255:12)
     at Parser.parseMaybeAssignAllowIn (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:17)
    at Parser.parseExprListItem (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12007:18)
    at Parser.parseExprList (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11979:22)
    at Parser.parseArrayLike (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11879:26)
    at Parser.parseExprAtom (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11148:23)
    at Parser.parseExprSubscripts (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10870:23)
    at Parser.parseUpdate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10853:21)
    at Parser.parseMaybeUnary (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10829:23)
    at Parser.parseMaybeUnaryOrPrivate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10667:61)
    at Parser.parseExprOps (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10672:23)
    at Parser.parseMaybeConditional (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10649:23)
    at Parser.parseMaybeAssign (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10610:21)
    at C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:39
    at Parser.allowInAnd (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12255:12)
    at Parser.parseMaybeAssignAllowIn (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:17)
    at Parser.parseExprListItem (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12007:18)
    at Parser.parseExprList (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11979:22)
    at Parser.parseArrayLike (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11879:26)
    at Parser.parseExprAtom (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:11148:23)
    at Parser.parseExprSubscripts (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10870:23)
    at Parser.parseUpdate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10853:21)
    at Parser.parseMaybeUnary (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10829:23)
    at Parser.parseMaybeUnaryOrPrivate (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10667:61)
    at Parser.parseExprOps (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10672:23)
    at Parser.parseMaybeConditional (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10649:23)
    at Parser.parseMaybeAssign (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10610:21)
    at C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:10580:39
    at Parser.allowInAnd (C:\snapshot\unveilr\node_modules\@babel\parser\lib\index.js:12255:12)

**Comment by r3x5ur** [comment]
@feiyangboy2  这个要提供一下样本哦，一般的包没看到过这个错误

**Comment by feiyangboy2** [comment]
[Uploading wxapkg.zip…]()

**Comment by feiyangboy2** [comment]
[wxapkg.zip](https://github.com/r3x5ur/unveilr/files/11177430/wxapkg.zip)
这是demo 所有包一起解包的时候就会出现这个错误。

**Comment by r3x5ur** [comment]
@feiyangboy2  提供 `wxappid`

**Comment by feiyangboy2** [comment]
@r3x5ur  id: wx950babf936508e51

**Comment by r3x5ur** [comment]
这是 `@babel/parser` 的 `bug` https://github.com/babel/babel/issues/14128
