### ISSUE TITLE
 Parsing wxml failed, Noticable generics content  

### ISSUE THREAD

**Issue by githubjy** [r3x5ur/unveilr#82]
### unveilr版本

2.0.0-alpha.4

### NodeJs版本

v18.12.1

### 操作系统

windows

### 运行时命令

unveilr C:\Users\Downloads\wxpack

### 重现步骤(最好能上传反编译失败的样本)

[失败样本.zip](https://github.com/r3x5ur/unveilr/files/11242305/default.zip)
[wxpack.zip](https://github.com/r3x5ur/unveilr/files/11242307/wxpack.zip)

### 预期结果

success

### 实际结果

 Error: Parsing wxml failed, Noticable generics content: [object Object]
    at Object.V [as parseWxml] (C:\Users\AppData\Roaming\npm\node_modules\unveilr\dist\parser-224a3ce2.js:7:485215)
    at async WxmlParser.parseV1 (C:\Users\AppData\Roaming\npm\node_modules\unveilr\dist\traverse-f66c5c3b.js:7:25121)

**Comment by r3x5ur** [comment]
https://github.com/r3x5ur/unveilr/releases/tag/v2.0.0

**Comment by r3x5ur** [comment]
#43
