### ISSUE TITLE
[Bug]:  plugin-private:// 导致的写入磁盘失败

### ISSUE THREAD

**Issue by Drzad1024** [r3x5ur/unveilr#88]
### unveilr版本

2.0.0

### NodeJs版本

v16.5.0

### 操作系统

windows

### 运行时命令

unveilr wx -i wx3484805679bf714f /path/to/dir/1.wxapkg -f

### wcc版本

v0.5vv_20200413_syb_scopedata

### 重现步骤(最好能上传反编译失败的样本)

Windows下输入命令“unveilr wx -i wx3484805679bf714f /wxapkg/1.wxapkg -f” 报错

![error](https://user-images.githubusercontent.com/15171744/232663746-90ebe1de-adc0-4279-b750-1113c6bfeb7e.png)

### 预期结果

解压出全部代码

### 实际结果

```
[ERROR] 11:26:11 <Exception> Error: ENOENT: no such file or directory, mkdir 'D:\wxapkg\1\__plugin__\wxfab2bf944bfc4da6\pages\index\plugin-private:\wxfab2bf944bfc4da6\components\navigation_bar'
    at Object.mkdirSync (fs.js:1014:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1639:33)
    at PathController.mkdir (C:\snapshot\unveilr\dist\traverse-11918978.js:7:6913)
    at SaveController.saveFile (C:\snapshot\unveilr\dist\traverse-11918978.js:7:10461)
    at C:\snapshot\unveilr\dist\traverse-11918978.js:7:11177
    at Array.map (<anonymous>)
    at SaveController.flashDisk (C:\snapshot\unveilr\dist\traverse-11918978.js:7:11052)
    at Object.flashDisk (C:\snapshot\unveilr\dist\traverse-11918978.js:7:11628)
    at y.saveFiles (C:\snapshot\unveilr\dist\index.js:7:15927)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

同时解压了部分的文件，但都是0KB
![dir](https://user-images.githubusercontent.com/15171744/232663878-af21bb66-90ce-4f9b-bfc1-2f8afe104d62.png)

### 其他信息

我找到了那个APP的wxapkg文件并放在了D盘wxapkg目录下

**Comment by Drzad1024** [comment]
[wx3484805679bf714f.zip](https://github.com/r3x5ur/unveilr/files/11257703/wx3484805679bf714f.zip)
这是wxapkg包

**Comment by r3x5ur** [comment]
感谢提交，正在处理中

**Comment by r3x5ur** [comment]
等新版本吧发自我的 iPhone在 2023年4月18日，15:33，Drzad ***@***.***> 写道：﻿
好的，请问我该怎么更新你修改的部分，让我能够使用修复过的应用呢？

**Comment by Drzad1024** [comment]
> 

好的，感谢
