### ISSUE TITLE
MacOS无法使用

### ISSUE THREAD

**Issue by ikilobyte** [r3x5ur/unveilr#9]
**Describe the bug**

**To Reproduce**/**复现过程**
```bash 
wxupk --help
```

**Expected behavior**/**预期结果**

**Actual behavior**/**实际结果**
```bash
env: node\r: No such file or directory
```

**Screenshots**/**相关截图**

**运行环境、版本信息**<br/>
**Desktop (please complete the following information):**
 - OS: MacOS
 - NodeJS: v18.12.1
 - Version: 1.0.1

**Additional context**/**其他描述**

**Comment by bopo** [comment]
我已经做了pr https://github.com/bopo/wxapkg-unpacker

**Comment by r3x5ur** [comment]
@bopo 解密模块能正常使用吗

**Comment by ikilobyte** [comment]
> 我已经做了pr 尚未合并 可以到这个仓库里取 MacOS 支持的版本，目前支持M1芯片 https://github.com/bopo/wxapkg-unpacker

ok，我试一下

**Comment by ikilobyte** [comment]
@bopo 
还是不能用，有报错，我的`.wxapkg`是从MacOS版小程序获取的，是否和这个有关系？

```bash
yarn wxupk ~/Documents/wxapkg/f6de052da5316347d90f07ff05982386.wxapkg
```
- 报错信息
```bash

┬ ┬─┐ ┬┌─┐┌─┐┬┌─┌─┐   ┬ ┬┌┐┌┌─┐┌─┐┌─┐┬┌─┌─┐┬─┐
│││┌┴┬┘├─┤├─┘├┴┐│ ┬───│ ││││├─┘├─┤│  ├┴┐├┤ ├┬┘
└┴┘┴ └─┴ ┴┴  ┴ ┴└─┘   └─┘┘└┘┴  ┴ ┴└─┘┴ ┴└─┘┴└─
                      version v1.0.1
                      author @r3x5ur

[INFO]  2023/03/09 11:00:58 wxunpacker Logger level: INFO
[INFO]  2023/03/09 11:00:58 wxunpacker Clear old package is turned on.
[INFO]  2023/03/09 11:00:58 wxunpacker Unpack file /Users/sunny/Documents/wxapkg/f6de052da5316347d90f07ff05982386.wxapkg
/Users/sunny/Documents/project/web/wxapkg-unpacker/packages/unpacker/src/wuWxapkg.js:24
  if (firstMark !== 0xbe || lastMark !== 0xed) throw Error('Magic number is not correct!')
                                               ^

Error: Magic number is not correct!
    at header (/Users/sunny/Documents/project/web/wxapkg-unpacker/packages/unpacker/src/wuWxapkg.js:24:54)
    at /Users/sunny/Documents/project/web/wxapkg-unpacker/packages/unpacker/src/wuWxapkg.js:224:42
    at /Users/sunny/Documents/project/web/wxapkg-unpacker/packages/unpacker/src/wuLib.js:105:10
    at agent (/Users/sunny/Documents/project/web/wxapkg-unpacker/packages/unpacker/src/wuLib.js:66:17)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nobita0522** [comment]
这个已经是能用了。只是这个小程序做了特殊处理

**Comment by ikilobyte** [comment]
@nobita0522 是不是只能解密原生开发的小程序？比如uni-app开发的小程序是不是用不了？

**Comment by nobita0522** [comment]
> @nobita0522 是不是只能解密原生开发的小程序？比如uni-app开发的小程序是不是用不了？

目前也在研究怎么回事，有结论了回复你

**Comment by nobita0522** [comment]
> 我已经做了pr 尚未合并 可以到这个仓库里取 MacOS 支持的版本，目前支持M1芯片 https://github.com/bopo/wxapkg-unpacker

还是不行，是不是芯片造成成，我这边是intel 7的mac ，os12.6 调用的时候报错wxunpacker {"errno":-86,"code":"Unknown system error -86","syscall":"spawn"}，晚点回家试一下m2的会不会有这个问题
